package internal

import (
	"strings"
	"testing"
)

var tachyon = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestDaySevenPartOne(t *testing.T) {
	d := DaySeven{}
	sol := d.SolvePartOne(strings.Split(tachyon, "\n"))

	if sol != 21 {
		t.Fatalf("expected 21, got: %d", sol)
	}
}

func TestDaySevenPartTwo(t *testing.T) {
	d := DaySeven{}
	sol := d.SolvePartTwo(strings.Split(tachyon, "\n"))

	if sol != 40 {
		t.Fatalf("expected 40, got: %d", sol)
	}
}
